import { jsPDF } from "jspdf"
import { formatOriginalSchedules, formatProposedArrangement } from "@/lib/schedule-adjustment/arrangement"
import type { ScheduleAdjustmentRequestRow } from "@/lib/schedule-adjustment/types"

type RosterRow = {
  student_display_name?: string
  campus_student_id?: string | null
  email?: string | null
  status?: string | null
  signature_name?: string | null
  signed_at?: string | Date | null
  document_version?: number | null
}

function statusLabel(status: string | null | undefined) {
  if (status === "agreed") return "Agreed"
  if (status === "concern" || status === "declined") return "Concern"
  return "Pending"
}

function fmtWhen(value: unknown) {
  if (!value) return "—"
  const d = new Date(String(value))
  if (Number.isNaN(d.getTime())) return "—"
  return d.toLocaleString("en-US", { timeZone: "America/Chicago" })
}

export function buildConsentReportPdf(params: {
  request: ScheduleAdjustmentRequestRow
  instructorName: string
  courseTitle: string
  semester: string
  generatedBy: string
  roster: RosterRow[]
  counts: { total: number; agreed: number; declined: number; pending: number }
}) {
  const pdf = new jsPDF("p", "mm", "a4")
  const pageW = pdf.internal.pageSize.getWidth()
  let y = 18

  const add = (text: string, size = 11, bold = false) => {
    pdf.setFont("helvetica", bold ? "bold" : "normal")
    pdf.setFontSize(size)
    const lines = pdf.splitTextToSize(text, pageW - 28)
    pdf.text(lines, 14, y)
    y += lines.length * (size * 0.45) + 2
  }

  add("CourseCollab Student Consent Report", 16, true)
  add("Schedule Change Review and Student Consent", 12, true)
  y += 2
  add(`Course: ${params.courseTitle}`)
  add(`Section: ${params.request.section_code ?? "—"}`)
  add(`Semester: ${params.semester}`)
  add(`Instructor: ${params.instructorName}`)
  add(`Schedule change request ID: ${params.request.id}`)
  add(`Document version: ${params.request.consent_document_version}`)
  add(`Effective date: ${String(params.request.effective_date ?? "—").slice(0, 10)}`)
  y += 2
  add("Original schedule", 12, true)
  add(formatOriginalSchedules(params.request))
  y += 1
  add("Final proposed schedule", 12, true)
  add(formatProposedArrangement(params.request))
  y += 2
  add(`Total enrolled students: ${params.counts.total}`)
  add(`Total students consenting: ${params.counts.agreed}`)
  add(`Total students with concerns: ${params.counts.declined}`)
  add(`Total pending: ${params.counts.pending}`)
  const pct = params.counts.total ? Math.round((params.counts.agreed / params.counts.total) * 100) : 0
  add(`Consent percentage: ${pct}%`)
  add(`Finalized: ${fmtWhen(params.request.finalized_at)}`)
  y += 3
  add("Student roster", 12, true)

  for (const row of params.roster) {
    if (y > 270) {
      pdf.addPage()
      y = 18
    }
    add(
      `${row.student_display_name ?? "Student"}  |  ${row.campus_student_id ?? "—"}  |  ${row.email ?? "—"}  |  ${statusLabel(row.status)}  |  ${row.signature_name ?? "—"}  |  ${fmtWhen(row.signed_at)}  |  v${row.document_version ?? params.request.consent_document_version}`,
      9,
    )
  }

  if (y > 250) {
    pdf.addPage()
    y = 18
  }
  y += 4
  add(
    "This report was generated from authenticated CourseCollab student consent records associated with the identified schedule adjustment request.",
    10,
    true,
  )
  add(`Generated by: ${params.generatedBy}`)
  add(`Generated date: ${fmtWhen(new Date())}`)
  add(`Instructor: ${params.instructorName}`)
  add(`CourseCollab record ID: ${params.request.id}`)

  return pdf.output("arraybuffer")
}
