import type { CoraModelProfile, CoraProfileDefinition } from "@/lib/cora/models/types"

export const CORA_PROFILE_DEFINITIONS: Record<CoraModelProfile, CoraProfileDefinition> = {
  lite: {
    profile: "lite",
    label: "Cora Lite",
    description: "Inexpensive conversational help after premium allowance is exhausted.",
    costClass: "inexpensive",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: false,
    maxOutputTokens: 500,
    temperature: 0.3,
    allowedInLite: true,
    escalationTarget: null,
  },
  fast: {
    profile: "fast",
    label: "Fast",
    description: "Classification, routing, metadata extraction, simple transforms.",
    costClass: "inexpensive",
    supportsTools: false,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: false,
    supportsReasoning: false,
    maxOutputTokens: 400,
    temperature: 0.1,
    allowedInLite: true,
    escalationTarget: "standard",
  },
  standard: {
    profile: "standard",
    label: "Standard",
    description: "Normal Cora conversation, authoring, and career assistance.",
    costClass: "standard",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: false,
    maxOutputTokens: 1400,
    temperature: 0.65,
    allowedInLite: false,
    escalationTarget: "reasoning",
  },
  tutor: {
    profile: "tutor",
    label: "Tutor",
    description: "Educational explanations, Guide Me, Solve With Me, walkthroughs.",
    costClass: "standard",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: false,
    maxOutputTokens: 1800,
    temperature: 0.55,
    allowedInLite: false,
    escalationTarget: "reasoning",
  },
  coding: {
    profile: "coding",
    label: "Coding",
    description: "CodeBench, debugging, code review, execution traces.",
    costClass: "standard",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: false,
    maxOutputTokens: 2800,
    temperature: 0.4,
    allowedInLite: false,
    escalationTarget: "reasoning",
  },
  vision: {
    profile: "vision",
    label: "Vision",
    description: "Image extraction for circuits, handwriting, diagrams, screenshots.",
    costClass: "standard",
    supportsTools: false,
    supportsVision: true,
    supportsStructuredOutput: true,
    supportsStreaming: false,
    supportsReasoning: false,
    maxOutputTokens: 1200,
    temperature: 0.2,
    allowedInLite: false,
    escalationTarget: "tutor",
  },
  agent: {
    profile: "agent",
    label: "Agent",
    description: "Tool selection and multi-step CourseCollab operations.",
    costClass: "standard",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: false,
    maxOutputTokens: 1600,
    temperature: 0.4,
    allowedInLite: false,
    escalationTarget: "reasoning",
  },
  long_context: {
    profile: "long_context",
    label: "Long context",
    description: "Large lectures, syllabi, and document analysis.",
    costClass: "premium",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: false,
    maxOutputTokens: 2400,
    temperature: 0.4,
    allowedInLite: false,
    escalationTarget: "reasoning",
  },
  reasoning: {
    profile: "reasoning",
    label: "Reasoning",
    description: "Difficult STEM, assessment validation, sophisticated analysis.",
    costClass: "premium",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: true,
    maxOutputTokens: 2400,
    temperature: 0.35,
    allowedInLite: false,
    escalationTarget: "advanced_reasoning",
  },
  advanced_reasoning: {
    profile: "advanced_reasoning",
    label: "Advanced reasoning",
    description: "Exceptionally difficult or high-stakes analysis. Use sparingly.",
    costClass: "frontier",
    supportsTools: true,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: true,
    supportsReasoning: true,
    maxOutputTokens: 3200,
    temperature: 0.3,
    allowedInLite: false,
    escalationTarget: null,
  },
  verifier: {
    profile: "verifier",
    label: "Verifier",
    description: "Independent validation of high-impact generated artifacts.",
    costClass: "premium",
    supportsTools: false,
    supportsVision: false,
    supportsStructuredOutput: true,
    supportsStreaming: false,
    supportsReasoning: true,
    maxOutputTokens: 1600,
    temperature: 0.1,
    allowedInLite: false,
    escalationTarget: null,
  },
  embedding: {
    profile: "embedding",
    label: "Embedding",
    description: "Vector embeddings for retrieval. Not a chat model.",
    costClass: "inexpensive",
    supportsTools: false,
    supportsVision: false,
    supportsStructuredOutput: false,
    supportsStreaming: false,
    supportsReasoning: false,
    maxOutputTokens: 0,
    temperature: 0,
    allowedInLite: true,
    escalationTarget: null,
  },
}

export function getCoraProfileDefinition(profile: CoraModelProfile): CoraProfileDefinition {
  return CORA_PROFILE_DEFINITIONS[profile]
}
