/** Module 6 — AI Learning Accelerator knowledge check (22 questions). */

export const AI_BOOTCAMP_MODULE_6_QUIZ: Array<Record<string, unknown>> = [
  {
    id: "q1",
    prompt: "The core goal of this module is…",
    options: [
      "How can AI do my schoolwork for me?",
      "How can AI help me become a stronger, faster, more independent learner?",
      "How can I hide AI use from instructors?",
      "How can AI replace all studying?",
    ],
    correctIndex: 1,
  },
  {
    id: "q2",
    prompt: "True or False: AI should support thinking, not replace thinking.",
    options: ["True", "False"],
    correctIndex: 0,
    trueFalse: true,
  },
  {
    id: "q3",
    prompt: "Better AI tutoring looks like…",
    options: [
      "Student asks for answer → AI gives answer → done",
      "Student attempts → AI asks questions → hints → student tries again → practice",
      "AI completes the assignment while student watches",
      "Student never attempts problems",
    ],
    correctIndex: 1,
  },
  {
    id: "q4",
    prompt: "The CourseCollab tutor framework includes… (Select ALL that apply)",
    options: ["Subject and level", "Goal and teaching style", "Interaction rules and assessment", "Your social media password"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q5",
    prompt: "The Smart Note Pipeline transforms one source into…",
    options: [
      "Only a longer copy of the same text",
      "Summary, study guide, flashcards, quiz, and concept map",
      "Fake citations",
      "A finished essay to submit unchanged",
    ],
    correctIndex: 1,
  },
  {
    id: "q6",
    prompt: "After generating study materials from notes, students should…",
    options: [
      "Trust AI completely without checking",
      "Compare outputs to the original for omissions or invented facts",
      "Delete the original notes",
      "Skip practice entirely",
    ],
    correctIndex: 1,
  },
  {
    id: "q7",
    prompt: "The Explanation Ladder helps when you…",
    options: [
      "Repeat the same vague question",
      "Change how information is explained (simple → analogy → example → test)",
      "Ask AI to take the exam",
      "Memorize without understanding",
    ],
    correctIndex: 1,
  },
  {
    id: "q8",
    prompt: "Active recall means…",
    options: [
      "Rereading notes until they feel familiar",
      "Retrieving information from memory without looking at notes",
      "Copying definitions repeatedly",
      "Letting AI memorize for you",
    ],
    correctIndex: 1,
  },
  {
    id: "q9",
    prompt: "Exam preparation should begin with…",
    options: ["Random cramming", "Diagnosis of what you know and don't know", "Predicting exact exam questions", "Skipping practice"],
    correctIndex: 1,
  },
  {
    id: "q10",
    prompt: "True or False: AI can reliably predict exact exam questions.",
    options: ["True", "False"],
    correctIndex: 1,
    trueFalse: true,
  },
  {
    id: "q11",
    prompt: "In the priority matrix, Important + Not Urgent tasks should be…",
    options: ["Scheduled deliberately", "Ignored forever", "Done only at 2 a.m.", "Delegated to AI without review"],
    correctIndex: 0,
  },
  {
    id: "q12",
    prompt: "A good AI weekly study plan should be…",
    options: [
      "Realistic — including sleep, breaks, and buffer time",
      "Every minute scheduled with no rest",
      "Based only on AI guesses about your grades",
      "Copied without checking deadlines",
    ],
    correctIndex: 0,
  },
  {
    id: "q13",
    prompt: "Responsible research includes…",
    options: [
      "Never cite a source you haven't confirmed exists and supports your claim",
      "Cite whatever AI lists without checking",
      "Use only social media posts",
      "Skip verification for speed",
    ],
    correctIndex: 0,
  },
  {
    id: "q14",
    prompt: "Which is usually in the GREEN zone (subject to instructor policy)?",
    options: [
      "Explain a concept and generate practice questions",
      "Complete an exam for you",
      "Fabricate lab results",
      "Submit AI work unchanged as your own",
    ],
    correctIndex: 0,
  },
  {
    id: "q15",
    prompt: "RED zone academic AI use includes… (Select ALL that apply)",
    options: ["Completing exams with AI", "Fabricating citations", "Circumventing plagiarism rules", "Explaining a concept with AI when allowed"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q16",
    prompt: "AI writing support should preserve…",
    options: [
      "Student ideas, voice, judgment, and responsibility",
      "Only AI-generated text with no student input",
      "Fake personal experiences",
      "Anonymous submission without review",
    ],
    correctIndex: 0,
  },
  {
    id: "q17",
    prompt: "The L-E-A-R-N model stands for…",
    options: [
      "Learn · Engage · Assess · Reflect · Next step",
      "Lazy · Easy · Automatic · Robotic · Never study",
      "Listen · Escape · Avoid · Repeat · Nap",
      "Lecture · Exam · Answer · Repeat · Network",
    ],
    correctIndex: 0,
  },
  {
    id: "q18",
    prompt: "AI augmentation vs dependence: augmentation means…",
    options: [
      "Student attempts → AI supports → student practices → capability increases",
      "AI answers everything → student practices less → struggles without AI",
      "Never using AI",
      "Letting AI choose your major",
    ],
    correctIndex: 0,
  },
  {
    id: "q19",
    prompt: "Metacognition is…",
    options: [
      "Thinking about how you learn and what to change",
      "Memorizing AI tool names only",
      "Avoiding all reflection",
      "Copying classmates' workflows",
    ],
    correctIndex: 0,
  },
  {
    id: "q20",
    prompt: "Before using AI on schoolwork, PAUSE reminds you to check…",
    options: [
      "Privacy, Accuracy, Understand, Safety & Fairness, Explain & Evaluate",
      "Password, Access, Upload, Save, Exit only",
      "Nothing — always use AI first",
      "Only whether the tool is free",
    ],
    correctIndex: 0,
  },
  {
    id: "q21",
    prompt: "The best AI learning system often…",
    options: [
      "Uses several specialized tools rather than one tool for everything",
      "Forces one chatbot to do research, design, and coding at once",
      "Avoids any verification",
      "Replaces all human teachers",
    ],
    correctIndex: 0,
  },
  {
    id: "q22",
    prompt: "Your AI Study Toolkit should include reusable prompts for… (Select ALL that apply)",
    options: ["Tutor, notes, quizzes, and exam prep", "Research and writing feedback", "Responsible AI checklist", "Submitting unchecked AI essays"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
]
