/** Module 5 — AI Creator Studio knowledge check (20 questions). */

export const AI_BOOTCAMP_MODULE_5_QUIZ: Array<Record<string, unknown>> = [
  {
    id: "q1",
    prompt: "The AI Creator Workflow teaches that creation is not just pressing Generate — it includes…",
    options: [
      "Only typing one prompt and publishing immediately",
      "Brief → prompt → generate → evaluate → refine → combine → human edit → publish",
      "Avoiding all human review",
      "Using only one AI tool forever",
    ],
    correctIndex: 1,
  },
  {
    id: "q2",
    prompt: "In C-R-E-A-T-E, the **R** stands for…",
    options: ["Random", "Requirements — audience and goals", "Robot", "Revision only"],
    correctIndex: 1,
  },
  {
    id: "q3",
    prompt: "True or False: AI-generated logos are automatically safe to use commercially without review.",
    options: ["True", "False"],
    correctIndex: 1,
    trueFalse: true,
  },
  {
    id: "q4",
    prompt: "Before generating multiple assets, a style guide helps with…",
    options: [
      "Random colors on every poster",
      "Visual and brand consistency across media",
      "Hiding AI use from viewers",
      "Skipping human editing",
    ],
    correctIndex: 1,
  },
  {
    id: "q5",
    prompt: "Grounded image prompts should specify… (Select ALL that apply)",
    options: ["Subject and scene", "Composition and style", "Lighting and format", "Your password"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q6",
    prompt: "Graphic design differs from image generation because design organizes…",
    options: [
      "Typography, hierarchy, spacing, alignment, and branding",
      "Only random pixels",
      "Database passwords",
      "Wi-Fi settings",
    ],
    correctIndex: 0,
  },
  {
    id: "q7",
    prompt: "Responsible voice use includes…",
    options: [
      "Cloning anyone's voice without consent",
      "Never cloning voices without authorization; disclose synthetic media when needed",
      "Using fake emergency calls",
      "Hiding that audio is AI-generated in all cases",
    ],
    correctIndex: 1,
  },
  {
    id: "q8",
    prompt: "Before publishing, C-R-E-A-T-O-R checks include… (Select ALL that apply)",
    options: ["Correct (accurate facts)", "Ethical and responsible", "Reviewed by a human", "Skip accessibility"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q9",
    prompt: "A storyboard before video generation helps…",
    options: [
      "Prevent random unrelated clips",
      "Guarantee viral success",
      "Remove the need for scripts",
      "Avoid all editing",
    ],
    correctIndex: 0,
  },
  {
    id: "q10",
    prompt: "Responsible marketing with AI must avoid…",
    options: [
      "Fake testimonials and invented statistics",
      "Clear audience targeting",
      "Honest product descriptions",
      "Disclosing sponsorship when required",
    ],
    correctIndex: 0,
  },
  {
    id: "q11",
    prompt: "Multimodal generative AI can combine…",
    options: [
      "Text, images, audio, video, and code in one project",
      "Only plain text",
      "Only spreadsheets",
      "Only passwords",
    ],
    correctIndex: 0,
  },
  {
    id: "q12",
    prompt: "Iterative creation means professionals…",
    options: [
      "Accept Version 1 without review",
      "Keep prompt/output history and refine deliberately",
      "Never change prompts",
      "Delete all earlier versions without comparison",
    ],
    correctIndex: 1,
  },
  {
    id: "q13",
    prompt: "Human-centered design asks whether the result is…",
    options: [
      "Useful, usable, accessible, trustworthy, and responsible",
      "Only colorful",
      "Only longer than one page",
      "Free of any human input",
    ],
    correctIndex: 0,
  },
  {
    id: "q14",
    prompt: "AI-assisted app prototyping at beginner level focuses on…",
    options: [
      "Idea → requirements → interface → prototype → test → improve",
      "Deploying untested code to production immediately",
      "Skipping user needs",
      "Sharing confidential data in prompts",
    ],
    correctIndex: 0,
  },
  {
    id: "q15",
    prompt: "True or False: AI expands the creator's toolbox but humans still approve purpose, ethics, and final quality.",
    options: ["True", "False"],
    correctIndex: 0,
    trueFalse: true,
  },
  {
    id: "q16",
    prompt: "For event flyer workflow, best practice is…",
    options: [
      "Generate background → add typography manually → check readability → export",
      "Let AI render all text inside the image without checking",
      "Publish without reviewing school policy",
      "Use copyrighted logos without permission",
    ],
    correctIndex: 0,
  },
  {
    id: "q17",
    prompt: "A creative brief should define… (Select ALL that apply)",
    options: ["Goal and audience", "Tone and deliverables", "Constraints", "Nothing — prompt randomly"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q18",
    prompt: "Prompt chains are stronger than one giant prompt because…",
    options: [
      "They separate research, draft, critique, human review, and revision",
      "They eliminate human review",
      "They guarantee factual accuracy",
      "They only work for trivia",
    ],
    correctIndex: 0,
  },
  {
    id: "q19",
    prompt: "AI content authenticity may require disclosure when…",
    options: [
      "Viewers might reasonably assume media depicts a real event",
      "You use a plain text outline",
      "You brainstorm in private",
      "You delete your prompts",
    ],
    correctIndex: 0,
  },
  {
    id: "q20",
    prompt: "Enterprise creative teams typically use…",
    options: [
      "Prompt → Generate → Review → Approve → Publish",
      "Prompt → Publish with no review",
      "Only one intern and no oversight",
      "Hidden AI use in all cases",
    ],
    correctIndex: 0,
  },
]
