/** Module 7 — AI Career Accelerator knowledge check (24 questions). */

export const AI_BOOTCAMP_MODULE_8_QUIZ: Array<Record<string, unknown>> = [
  {
    id: "q1",
    prompt: "The core goal of this module is…",
    options: [
      "How can AI get me a job?",
      "How can AI help me become a stronger candidate, communicator, learner, and problem solver?",
      "How can I hide AI use from employers?",
      "How can AI replace all professional judgment?",
    ],
    correctIndex: 1,
  },
  {
    id: "q2",
    prompt: "A better question than “Will AI take my job?” is…",
    options: [
      "How will AI change my future job?",
      "Which AI tool is coolest?",
      "How do I avoid all technology?",
      "Who will win the AI race?",
    ],
    correctIndex: 0,
  },
  {
    id: "q3",
    prompt: "AI augmentation means…",
    options: [
      "AI helps a person perform a task faster or better",
      "AI always eliminates the profession",
      "Humans never make decisions",
      "AI replaces all human connection",
    ],
    correctIndex: 0,
  },
  {
    id: "q4",
    prompt: "Future-ready professionals combine… (Select ALL that apply)",
    options: ["Domain knowledge", "AI fluency", "Human skills", "Continuous learning", "Avoiding all practice"],
    multiSelect: true,
    correctIndices: [0, 1, 2, 3],
  },
  {
    id: "q5",
    prompt: "The achievement formula for resume bullets is…",
    options: ["Action + Task + Result", "Random + Vague + Long", "Copy job posting only", "Invent experiences"],
    correctIndex: 0,
  },
  {
    id: "q6",
    prompt: "True or False: AI may improve how you describe experience but must never invent the experience.",
    options: ["True", "False"],
    correctIndex: 0,
    trueFalse: true,
  },
  {
    id: "q7",
    prompt: "ATS-friendly resumes prioritize…",
    options: [
      "Clear headings, relevant keywords, simple formatting, accurate skills",
      "Hidden keywords in white text",
      "Graphics-only layouts with no text",
      "Invented job titles",
    ],
    correctIndex: 0,
  },
  {
    id: "q8",
    prompt: "A cover letter should answer… (Select ALL that apply)",
    options: ["Why this opportunity?", "Why this organization?", "Why you?", "Why you never read the posting"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q9",
    prompt: "Professional enhancement with AI images should not become…",
    options: [
      "Professional misrepresentation",
      "Background cleanup when appropriate",
      "Authentic presentation",
      "Honest branding",
    ],
    correctIndex: 0,
  },
  {
    id: "q10",
    prompt: "Networking is…",
    options: [
      "Building genuine professional relationships over time",
      "Mass-spamming strangers for jobs",
      "Pretending to know people you don't",
      "Only asking for favors",
    ],
    correctIndex: 0,
  },
  {
    id: "q11",
    prompt: "STAR stands for…",
    options: [
      "Situation · Task · Action · Result",
      "Speed · Talk · Answer · Run",
      "Student · Teacher · AI · Robot",
      "Start · Try · Avoid · Repeat",
    ],
    correctIndex: 0,
  },
  {
    id: "q12",
    prompt: "AI mock interviews should…",
    options: [
      "Ask one question at a time and give feedback after you respond",
      "Provide model answers before you try",
      "Replace all human interview practice",
      "Guarantee job offers",
    ],
    correctIndex: 0,
  },
  {
    id: "q13",
    prompt: "An executive brief should include…",
    options: [
      "Topic, why it matters, key findings, opportunities, risks, recommendation, sources",
      "Only opinions with no evidence",
      "30 pages of unverified AI text",
      "Fake citations",
    ],
    correctIndex: 0,
  },
  {
    id: "q14",
    prompt: "Problem-first entrepreneurship starts with…",
    options: [
      "A meaningful problem someone experiences",
      "Building an app because AI is cool",
      "Copying a random startup",
      "Inventing fake customer testimonials",
    ],
    correctIndex: 0,
  },
  {
    id: "q15",
    prompt: "The professional productivity rule is…",
    options: [
      "Automate routine work — do not automate responsibility",
      "Automate accountability away",
      "Never review AI output",
      "Upload confidential data to any chatbot",
    ],
    correctIndex: 0,
  },
  {
    id: "q16",
    prompt: "A strong portfolio project page explains… (Select ALL that apply)",
    options: ["Problem and your role", "Process, tools, and results", "What you learned", "Only the AI tool name"],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q17",
    prompt: "Build your career around…",
    options: [
      "Clearly demonstrating relevant, authentic skills and experience",
      "Beating algorithms with tricks",
      "Inventing credentials",
      "Hiding all AI use always",
    ],
    correctIndex: 0,
  },
  {
    id: "q18",
    prompt: "Before using AI at work, ask… (Select ALL that apply)",
    options: [
      "Is this tool approved?",
      "Is this information confidential?",
      "Who remains accountable?",
      "Can I skip all review?",
    ],
    multiSelect: true,
    correctIndices: [0, 1, 2],
  },
  {
    id: "q19",
    prompt: "B-U-I-L-D stands for…",
    options: [
      "Brand · Upskill · Innovate · Leverage · Demonstrate",
      "Bot · Upload · Ignore · Lie · Delete",
      "Buy · Use · Install · Link · Download",
      "Basic · Unskilled · Idle · Lazy · Distracted",
    ],
    correctIndex: 0,
  },
  {
    id: "q20",
    prompt: "The career success flywheel includes…",
    options: [
      "Learn → Build → Document → Share → Connect → Apply → Reflect → Improve",
      "Prompt → Submit → Forget",
      "Only collecting certificates",
      "Avoiding all networking",
    ],
    correctIndex: 0,
  },
  {
    id: "q21",
    prompt: "Principle: Build evidence means…",
    options: [
      "Show projects, research, portfolios — not just claim “I know AI”",
      "Say you know AI without artifacts",
      "Let AI invent your resume",
      "Skip all documentation",
    ],
    correctIndex: 0,
  },
  {
    id: "q22",
    prompt: "AI + no expertise can produce…",
    options: [
      "Impressive mistakes — domain knowledge matters",
      "Perfect decisions always",
      "No need for human judgment",
      "Automatic leadership",
    ],
    correctIndex: 0,
  },
  {
    id: "q23",
    prompt: "Your 90-day action plan should include… (Select ALL that apply)",
    options: ["One skill to develop", "One project to build", "One person to connect with", "One opportunity to pursue"],
    multiSelect: true,
    correctIndices: [0, 1, 2, 3],
  },
  {
    id: "q24",
    prompt: "The ultimate goal is to become…",
    options: [
      "AI-ready + career-ready + future-ready",
      "AI-literate only with no evidence",
      "Dependent on AI for all decisions",
      "A tool memorizer with no communication skills",
    ],
    correctIndex: 0,
  },
]
