import type { CoraPermissionClaim, CoraPrincipalRole } from "@/lib/cora/security/types"
import type { CoraAgentToolName } from "@/lib/cora/tools/openai-tool-definitions"

/**
 * Capability → roles matrix (from CourseCollab Cora RBAC architecture).
 * Tools are never exposed outside these claims.
 */
export const ROLE_PERMISSIONS: Record<CoraPrincipalRole, readonly CoraPermissionClaim[]> = {
  student: [
    "read_own_profile",
    "read_own_grades",
    "read_own_attendance",
    "read_own_classroom_points",
    "read_own_assessments",
    "read_own_calendar",
    "read_own_notes",
    "read_own_flashcards",
    "read_own_lectures",
    "read_own_notifications",
    "search_enrolled_platform",
    "search_released_lectures",
    "create_own_flashcards",
    "create_own_notes",
    "create_own_practice",
    "create_own_study_plan",
    "create_own_calendar",
    "review_own_released_attempts",
    "read_assessment_integrity",
    "learn_concepts",
    "solve_steps",
    "code_assist",
    "circuit_assist",
  ],
  faculty: [
    "learn_concepts",
    "solve_steps",
    "code_assist",
    "circuit_assist",
    "create_course_flashcards",
    "generate_questions",
    "build_quizzes",
    "create_question_bank",
    "publish_course_announcements",
    "grade_assistance",
    "read_assigned_course",
    "read_assigned_students",
    "read_course_analytics",
    "search_enrolled_platform",
  ],
  admin: [
    "learn_concepts",
    "read_institution_analytics",
    "read_revenue_analytics",
    "platform_configuration",
    "security_center",
    "ai_governance",
    "executive_reports",
    "search_enrolled_platform",
  ],
}

/** Each executable tool requires at least one permission claim. */
export const TOOL_REQUIRED_PERMISSIONS: Record<CoraAgentToolName, readonly CoraPermissionClaim[]> = {
  get_student_summary: ["read_own_profile", "read_own_grades"],
  get_calendar_events: ["read_own_calendar"],
  get_assessments: ["read_own_assessments"],
  get_attendance: ["read_own_attendance"],
  get_classroom_points: ["read_own_classroom_points"],
  get_notifications: ["read_own_notifications"],
  get_lecture_progress: ["read_own_lectures"],
  get_flashcards_and_notes: ["read_own_flashcards", "read_own_notes"],
  search_platform: ["search_enrolled_platform"],
  search_lecture_materials: ["search_released_lectures", "read_assigned_course"],
  create_flashcards: ["create_own_flashcards"],
  create_study_note: ["create_own_notes"],
  propose_personal_flashcards: ["create_own_flashcards"],
  propose_personal_note: ["create_own_notes"],
  propose_calendar_study_sessions: ["create_own_calendar", "create_own_study_plan"],
  get_assessment_integrity: ["read_assessment_integrity", "read_own_assessments"],
  review_released_attempt: ["review_own_released_attempts", "read_own_grades"],
  propose_practice_quiz: ["create_own_practice"],
  propose_study_plan: ["create_own_study_plan"],
  create_practice_quiz: ["create_own_practice"],
  create_study_plan: ["create_own_study_plan"],
  get_faculty_course_summary: ["read_assigned_course", "read_course_analytics"],
  generate_question_drafts: ["generate_questions", "build_quizzes"],
  propose_question_bank_create: ["create_question_bank", "generate_questions"],
  propose_announcement: ["publish_course_announcements", "read_assigned_course"],
  propose_assessment_from_bank: ["build_quizzes", "create_question_bank", "read_assigned_course"],
  propose_remediation_quiz_plan: ["build_quizzes", "create_question_bank", "read_course_analytics"],
  propose_message_send: ["read_assigned_students", "read_assigned_course"],
  analyze_assessment_results: ["read_course_analytics", "read_assigned_course"],
  propose_syllabus_section: ["read_assigned_course"],
  propose_lecture_shell: ["read_assigned_course"],
  create_faculty_flashcard_deck: ["create_course_flashcards"],
  get_admin_platform_snapshot: ["read_institution_analytics", "executive_reports"],
  get_admin_revenue_summary: ["read_revenue_analytics"],
  get_admin_security_overview: ["security_center", "ai_governance"],
  get_admin_governance_hints: ["ai_governance", "executive_reports"],
  search_admin_faculty: ["read_institution_analytics", "executive_reports"],
  search_admin_students: ["read_institution_analytics", "executive_reports"],
  search_admin_courses: ["read_institution_analytics", "executive_reports"],
  list_admin_academic_terms: ["read_institution_analytics", "executive_reports"],
  get_admin_student_success: ["read_institution_analytics", "executive_reports"],
  get_admin_enrollment_analytics: ["read_institution_analytics", "executive_reports"],
  list_admin_password_resets: ["security_center", "platform_configuration"],
  propose_admin_password_reset_decision: ["security_center", "platform_configuration"],
  search_admin_submission_issues: ["read_institution_analytics", "security_center"],
  search_admin_system_logs: ["security_center", "platform_configuration"],
  search_admin_audit_logs: ["security_center", "ai_governance"],
}

export function permissionsForRole(role: CoraPrincipalRole): ReadonlySet<CoraPermissionClaim> {
  return new Set(ROLE_PERMISSIONS[role])
}
