/**
 * Code authenticity/authorship detection - direct function (no internal HTTP fetch).
 * Used by codebench/submit to avoid internal fetches that can fail with Vercel deployment protection.
 */

import { createForFeature } from "@/lib/resolve-feature-ai-model"
import OpenAI from "openai"

const isOpenAIConfigured = !!process.env.OPENAI_API_KEY
const openai = isOpenAIConfigured ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY }) : null

export interface AuthorshipResult {
  authenticity_score: number
  ai_likelihood: number
  reasoning: string
  flagged_features: string[]
}

export async function checkCodeAuthorship(
  code: string,
  language: string = "cpp"
): Promise<AuthorshipResult> {
  if (!isOpenAIConfigured || !openai) {
    return {
      authenticity_score: 50,
      ai_likelihood: 0.5,
      reasoning: "AI authorship detection is not configured.",
      flagged_features: [],
    }
  }

  const prompt = `You are a code authenticity evaluator. Determine whether the following ${language} code was written by a human student or generated by AI.

Analyze using these criteria:

1. **Variable Naming Patterns**
   - AI: Descriptive, consistent camelCase (calculateAverage, studentScore, processData)
   - Human: Short names (a, temp, num), inconsistent naming, mix of conventions

2. **Formatting Consistency**
   - AI: Perfect indentation, consistent spacing, uniform brace style
   - Human: Inconsistent formatting, messy whitespace, occasional misalignment

3. **Comment Style and Tone**
   - AI: Full sentences, perfect grammar, step-by-step explanations, overly descriptive
   - Human: Brief comments, occasional typos, inconsistent commenting, vague descriptions

4. **Code Structure**
   - AI: Overly clean structure, perfect best practices, no unused variables
   - Human: Occasional inefficiencies, minor mistakes, unused variables, personal quirks

5. **Advanced Features Usage**
   - AI: Automatically uses best practices (std::vector, smart pointers, modern C++)
   - Human: Mix of approaches, sometimes uses simpler/older patterns

6. **Perfection Level**
   - AI: Zero formatting mistakes, perfect consistency throughout
   - Human: Minor inconsistencies, occasional formatting quirks

Return a JSON object with this exact structure:
{
  "authenticity_score": <number 0-100, where 80-100 = likely human, 50-79 = mixed, 0-49 = likely AI>,
  "ai_likelihood": <number 0-1, probability of being AI-generated>,
  "reasoning": "<detailed explanation of your analysis, 2-3 sentences>",
  "flagged_features": ["<feature1>", "<feature2>", ...]
}

Examples of flagged features:
- "Perfect comment grammar throughout"
- "Step-by-step comments typical of ChatGPT"
- "Fully consistent camelCase naming"
- "Zero formatting mistakes"
- "Overly descriptive variable names"
- "Automatic use of modern C++ best practices"
- "No unused variables or code"

Code to analyze:
\`\`\`${language}
${code}
\`\`\`

Be thorough but fair. Consider that advanced students may write clean code.`

  try {
    const { content } = await createForFeature(openai, "codebench", {

      messages: [
        {
          role: "system",
          content:
            "You are an expert code authenticity evaluator. Analyze code patterns to determine if it was written by a human student or AI. Return only valid JSON.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.3,
      max_tokens: 1000,
      response_format: { type: "json_object" },
    })

    if (!content) {
      return {
        authenticity_score: 50,
        ai_likelihood: 0.5,
        reasoning: "Unable to analyze code authenticity.",
        flagged_features: [],
      }
    }

    const parsed = JSON.parse(content)
    const authenticity_score = Math.max(0, Math.min(100, parsed.authenticity_score || 50))
    const ai_likelihood = Math.max(0, Math.min(1, parsed.ai_likelihood || 0.5))

    return {
      authenticity_score,
      ai_likelihood,
      reasoning: parsed.reasoning || "Analysis completed.",
      flagged_features: Array.isArray(parsed.flagged_features) ? parsed.flagged_features : [],
    }
  } catch (err) {
    console.error("[Codebench Authorship] Error:", err)
    return {
      authenticity_score: 50,
      ai_likelihood: 0.5,
      reasoning: err instanceof Error ? err.message : "Failed to analyze code authenticity",
      flagged_features: [],
    }
  }
}
