/**
 * Drawer nav icons — Ionicons names → Lucide (web).
 * Ported from course-collab-mobile/expo/src/components/icons/ion-to-lucide-map.ts
 */

import type { LucideIcon } from "lucide-react"
import {
  Activity,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Award,
  BarChart2,
  Bell,
  BellOff,
  Book,
  BookOpen,
  Bookmark,
  Brush,
  Bug,
  Calendar,
  CalendarDays,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleArrowDown,
  CircleArrowRight,
  CircleCheck,
  CircleDot,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleX,
  ClipboardList,
  Clock,
  CloudOff,
  CloudUpload,
  Code,
  Compass,
  Copy,
  Delete,
  Download,
  Droplet,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Flag,
  Flame,
  Flower2,
  Folder,
  FolderOpen,
  Gamepad2,
  Gem,
  Gift,
  GitBranch,
  GitMerge,
  Globe,
  GraduationCap,
  Hand,
  Heart,
  HelpCircle,
  Home,
  Hourglass,
  Image,
  Images,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Medal,
  Megaphone,
  Menu,
  PanelLeft,
  PanelLeftClose,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Minimize2,
  Minus,
  Moon,
  Palette,
  Paperclip,
  Pause,
  PenLine,
  Pencil,
  Play,
  Plus,
  Presentation,
  Puzzle,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Snowflake,
  Sparkles,
  Square,
  SquareCheck,
  Star,
  Sun,
  Target,
  Terminal,
  Timer,
  ToggleLeft,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Type,
  User,
  UserMinus,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Wrench,
  X,
  Zap,
} from "lucide-react"
export type DrawerNavIconName = keyof typeof ION_TO_LUCIDE

/** Ionicons name → Lucide component. Brand logos use __brand__. */
export const ION_TO_LUCIDE: Partial<Record<DrawerNavIconName, LucideIcon | "__brand__">> = {
  add: Plus,
  "add-circle-outline": CirclePlus,
  "add-outline": Plus,
  "alarm-outline": Bell,
  "albums-outline": Layers,
  "alert-circle": CircleAlert,
  "alert-circle-outline": CircleAlert,
  "analytics-outline": BarChart2,
  "archive-outline": Archive,
  "arrow-back": ArrowLeft,
  "arrow-down": ArrowDown,
  "arrow-down-circle-outline": CircleArrowDown,
  "arrow-down-outline": ArrowDown,
  "arrow-forward": ArrowRight,
  "arrow-forward-circle": CircleArrowRight,
  "arrow-forward-circle-outline": CircleArrowRight,
  "arrow-undo-outline": RotateCcw,
  "arrow-up": ArrowUp,
  "arrow-up-circle-outline": ArrowUp,
  "arrow-up-outline": ArrowUp,
  "backspace-outline": Delete,
  "bar-chart-outline": BarChart2,
  "book-outline": BookOpen,
  "bookmark-outline": Bookmark,
  "brush-outline": Brush,
  bug: Bug,
  "bug-outline": Bug,
  bulb: Lightbulb,
  "bulb-outline": Lightbulb,
  "calendar-number-outline": CalendarDays,
  "calendar-outline": Calendar,
  "camera-outline": Camera,
  "cellular-outline": Smartphone,
  "chatbox-ellipses": MessageSquare,
  "chatbox-ellipses-outline": MessageSquare,
  "chatbox-outline": MessageSquare,
  "chatbubble-ellipses-outline": MessageCircle,
  "chatbubble-outline": MessageCircle,
  chatbubbles: MessagesSquare,
  "chatbubbles-outline": MessagesSquare,
  checkbox: SquareCheck,
  checkmark: Check,
  "checkmark-circle": CircleCheck,
  "checkmark-circle-outline": CircleCheck,
  "checkmark-done": CheckCheck,
  "checkmark-done-circle-outline": CircleCheck,
  "checkmark-done-outline": CheckCheck,
  "chevron-back": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-forward": ChevronRight,
  "chevron-up": ChevronUp,
  "clipboard-outline": ClipboardList,
  close: X,
  "close-circle": CircleX,
  "close-circle-outline": CircleX,
  "cloud-offline-outline": CloudOff,
  "cloud-upload-outline": CloudUpload,
  "code-slash": Code,
  "code-slash-outline": Code,
  "color-fill-outline": Droplet,
  "color-palette-outline": Palette,
  "compass-outline": Compass,
  "construct-outline": Wrench,
  "contract-outline": Minimize2,
  "copy-outline": Copy,
  "create-outline": PenLine,
  diamond: Gem,
  "diamond-outline": Gem,
  "document-attach-outline": Paperclip,
  "attach-outline": Paperclip,
  "document-outline": File,
  "document-text": FileText,
  "document-text-outline": FileText,
  "download-outline": Download,
  "easel-outline": Presentation,
  "ellipsis-horizontal": Ellipsis,
  "ellipsis-vertical": EllipsisVertical,
  "enter-outline": LogIn,
  "exit-outline": LogOut,
  "expand-outline": Maximize2,
  "extension-puzzle": Puzzle,
  "extension-puzzle-outline": Puzzle,
  "eye-off-outline": EyeOff,
  "eye-outline": Eye,
  "filter-outline": Filter,
  fitness: Target,
  "fitness-outline": Target,
  "flag-outline": Flag,
  flower: Flower2,
  "flower-outline": Flower2,
  flame: Flame,
  "flame-outline": Flame,
  flash: Zap,
  "flash-outline": Zap,
  "folder-open": FolderOpen,
  "folder-open-outline": FolderOpen,
  "folder-outline": Folder,
  "funnel-outline": Filter,
  "game-controller-outline": Gamepad2,
  "gift-outline": Gift,
  "git-branch-outline": GitBranch,
  "git-network-outline": GitMerge,
  "globe-outline": Globe,
  "grid-outline": LayoutDashboard,
  "hand-left-outline": Hand,
  "heart-outline": Heart,
  "help-buoy-outline": LifeBuoy,
  "help-circle-outline": HelpCircle,
  home: Home,
  "home-outline": Home,
  "hourglass-outline": Hourglass,
  "image-outline": Image,
  "images-outline": Images,
  "information-circle": Info,
  "information-circle-outline": Info,
  key: Key,
  "key-outline": Key,
  "layers-outline": Layers,
  leaf: Leaf,
  "leaf-outline": Leaf,
  "library-outline": Library,
  "link-outline": Link,
  "list-outline": List,
  "location-outline": MapPin,
  "lock-closed": Lock,
  "lock-closed-outline": Lock,
  "logo-apple": "__brand__",
  "logo-google": "__brand__",
  "mail-outline": Mail,
  "map-outline": Map,
  "medal-outline": Medal,
  "megaphone-outline": Megaphone,
  "menu-outline": Menu,
  "panel-left-outline": PanelLeft,
  "panel-left-close-outline": PanelLeftClose,
  mic: Mic,
  "mic-outline": Mic,
  "moon-outline": Moon,
  "notifications-off-outline": BellOff,
  "notifications-outline": Bell,
  "open-outline": ExternalLink,
  "options-outline": Ellipsis,
  "paper-plane": Send,
  "paper-plane-outline": Send,
  "pause-circle": CirclePause,
  "pause-circle-outline": CirclePause,
  "pencil-outline": Pencil,
  people: Users,
  "people-circle-outline": UsersRound,
  "people-outline": Users,
  "person-add-outline": UserPlus,
  "person-circle-outline": User,
  "person-outline": User,
  "person-remove-outline": UserMinus,
  "phone-portrait-outline": Smartphone,
  pin: MapPin,
  "pin-outline": MapPin,
  play: Play,
  "play-circle-outline": CirclePlay,
  "play-outline": Play,
  podium: BarChart2,
  "podium-outline": BarChart2,
  "pulse-outline": Activity,
  "radio-button-off": Circle,
  "radio-button-on": CircleDot,
  refresh: RefreshCw,
  "refresh-circle": RefreshCw,
  "refresh-outline": RefreshCw,
  remove: Minus,
  "remove-circle-outline": CircleMinus,
  "remove-outline": Minus,
  ribbon: Award,
  "ribbon-outline": Award,
  "rocket-outline": Rocket,
  "save-outline": Save,
  "scale-outline": SlidersHorizontal,
  school: GraduationCap,
  "school-outline": GraduationCap,
  search: Search,
  "search-outline": Search,
  send: Send,
  "send-outline": Send,
  "settings-outline": Settings,
  "share-outline": Share2,
  "shield-checkmark": ShieldCheck,
  "shield-checkmark-outline": ShieldCheck,
  "shield-outline": Shield,
  "shuffle-outline": Shuffle,
  snow: Snowflake,
  "snow-outline": Snowflake,
  sparkles: Sparkles,
  "sparkles-outline": Sparkles,
  "square-outline": Square,
  star: Star,
  "star-outline": Star,
  "stats-chart-outline": BarChart2,
  "stop-circle-outline": CircleStop,
  sunny: Sun,
  "sunny-outline": Sun,
  "swap-horizontal-outline": ArrowLeftRight,
  "sync-outline": RefreshCw,
  "terminal-outline": Terminal,
  "text-outline": Type,
  time: Clock,
  "time-outline": Clock,
  "timer-outline": Timer,
  "thumbs-up-outline": ThumbsUp,
  "thumbs-down-outline": ThumbsDown,
  "toggle-outline": ToggleLeft,
  "trash-outline": Trash2,
  "trending-up-outline": TrendingUp,
  trophy: Trophy,
  "trophy-outline": Trophy,
  "videocam-outline": Video,
  "warning-outline": TriangleAlert,
  water: Droplet,
  "water-outline": Droplet,
}

export function isBrandLogoIcon(name: DrawerNavIconName): boolean {
  return ION_TO_LUCIDE[name] === "__brand__" || name.startsWith("logo-")
}

export function resolveLucideIcon(name: DrawerNavIconName): LucideIcon {
  const mapped = ION_TO_LUCIDE[name]
  if (mapped && mapped !== "__brand__") {
    return mapped
  }

  const stripped = name.replace(/-outline$/, "") as DrawerNavIconName
  const strippedMap = ION_TO_LUCIDE[stripped]
  if (strippedMap && strippedMap !== "__brand__") {
    return strippedMap
  }

  return Circle
}
