/** Stable security-audit action names. Do not use free-form prose as the only identifier. */
export const SECURITY_AUDIT_ACTIONS = {
  AUTH_LOGIN_SUCCESS: "auth.login.success",
  AUTH_LOGIN_FAILURE: "auth.login.failure",
  AUTH_LOGOUT: "auth.logout",
  ROLE_GRANT: "role.grant",
  ROLE_REVOKE: "role.revoke",
  ROLE_CHANGE: "role.change",
  STUDENT_EXPORT: "student.export",
  GRADE_UPDATE: "grade.update",
  ASSESSMENT_OVERRIDE: "assessment.override",
  ASSESSMENT_SUBMIT_ON_BEHALF: "assessment.submit_on_behalf",
  ASSESSMENT_BULK_FINALIZE: "assessment.bulk_finalize",
  PLATFORM_PRIVILEGED_ACCESS: "platform.privileged_access",
  PLATFORM_STUDENT_RECORD_VIEW: "platform.student_record_view",
  AI_POLICY_UPDATE: "ai.policy.update",
  CORA_PLATFORM_INSTITUTION_SELECT: "cora.platform.institution_select",
  FILE_DOWNLOAD: "file.download",
  FILE_EXPORT: "file.export",
  FILE_DELETE: "file.delete",
  DATA_CLEAR: "data.clear",
  DEBUG_ACCESS: "debug.access",
  IDENTITY_PROVIDER_CREATE: "identity.provider.create",
  IDENTITY_PROVIDER_UPDATE: "identity.provider.update",
  IDENTITY_PROVIDER_DISABLE: "identity.provider.disable",
  IDENTITY_DOMAIN_CONFIGURE: "identity.domain.configure",
  AUTH_MFA_ENROLL: "auth.mfa.enroll",
  AUTH_MFA_VERIFY: "auth.mfa.verify",
  AUTH_MFA_RESET: "auth.mfa.reset",
  SESSION_REVOKE: "session.revoke",
  AUTH_SSO_START: "auth.sso.start",
  AUTH_SSO_SUCCESS: "auth.sso.success",
  AUTH_SSO_FAILURE: "auth.sso.failure",
  PRIVACY_EXPORT_STUDENT: "privacy.export.student",
  PRIVACY_EXPORT_INSTITUTION: "privacy.export.institution",
  PRIVACY_DELETION_REQUEST: "privacy.deletion.request",
  PRIVACY_DELETION_EXECUTE: "privacy.deletion.execute",
  PRIVACY_RETENTION_CHANGE: "privacy.retention.change",
  PRIVACY_RESEARCH_EXPORT: "privacy.research_export",
  PRIVACY_BLOB_MIGRATION: "privacy.blob_migration",
  PRIVACY_RLS_APPLY: "privacy.rls.apply",
  PRIVACY_RUNTIME_ROLE_CUTOVER: "privacy.runtime_role.cutover",
  INTEGRATION_CREATE: "integration.create",
  INTEGRATION_UPDATE: "integration.update",
  INTEGRATION_ENABLE: "integration.enable",
  INTEGRATION_DISABLE: "integration.disable",
  INTEGRATION_COURSE_MAP: "integration.course.map",
  INTEGRATION_IDENTITY_LINK: "integration.identity.link",
  INTEGRATION_ROSTER_PREVIEW: "integration.roster.preview",
  INTEGRATION_ROSTER_APPLY: "integration.roster.apply",
  INTEGRATION_GRADE_SEND: "integration.grade.send",
  INTEGRATION_GRADE_SUCCESS: "integration.grade.success",
  INTEGRATION_GRADE_FAILURE: "integration.grade.failure",
} as const

export type SecurityAuditAction =
  (typeof SECURITY_AUDIT_ACTIONS)[keyof typeof SECURITY_AUDIT_ACTIONS]

export const SECURITY_EVENT_SCOPES = ["institution", "platform", "system"] as const
export type SecurityEventScope = (typeof SECURITY_EVENT_SCOPES)[number]
