import OpenAI from "openai"
import { createForFeature } from "@/lib/resolve-feature-ai-model"
import {
  formatChatAsNoteMarkdown,
  type CoraWorkspaceActionMessage,
} from "@/lib/cora/workspace-actions"
import {
  formatPlatformSearchMarkdown,
  searchPlatformForStudent,
} from "@/lib/cora/platform-search"
import { generatePracticeQuizForStudent } from "@/lib/practice/generate-practice-quiz"

const openai = process.env.OPENAI_API_KEY
  ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
  : null

export async function exportChatToDigitalNote(
  studentDbId: number,
  messages: CoraWorkspaceActionMessage[],
  title?: string,
) {
  const noteTitle =
    title?.trim() ||
    `Cora chat · ${new Date().toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`
  const { bodyText } = formatChatAsNoteMarkdown(messages, noteTitle)
  const { createStudentDigitalNote } = await import(
    "@/lib/cora/services/create-student-digital-note"
  )
  return createStudentDigitalNote({
    studentDbId,
    title: noteTitle,
    bodyText,
  })
}

type FlashcardDraft = { front: string; back: string }

async function generateFlashcardsWithAi(
  topic: string,
  context: string,
  cardCount = 8,
): Promise<FlashcardDraft[]> {
  if (!openai) {
    throw new Error("AI is not configured")
  }

  const { content } = await createForFeature(openai, "content_tools", {
    messages: [
      {
        role: "system",
        content: `You create study flashcards for university engineering students. Return JSON only: {"cards":[{"front":"question or term","back":"concise answer"}]}. Create exactly ${Math.min(Math.max(cardCount, 4), 15)} cards. Front/back must be plain text (no markdown fences).`,
      },
      {
        role: "user",
        content: `Topic: ${topic}\n\nContext from the student's Cora session:\n${context.slice(0, 6000)}`,
      },
    ],
    response_format: { type: "json_object" },
    temperature: 0.4,
    max_completion_tokens: 2500,
  })

  const parsed = JSON.parse(content || "{}") as { cards?: FlashcardDraft[] }
  const cards = (parsed.cards ?? []).filter((c) => c.front?.trim() && c.back?.trim())
  if (cards.length === 0) throw new Error("AI returned no flashcards")
  return cards
}

async function generateStudyNoteWithAi(topic: string, context: string): Promise<string> {
  if (!openai) {
    throw new Error("AI is not configured")
  }

  const { content } = await createForFeature(openai, "content_tools", {
    messages: [
      {
        role: "system",
        content:
          "Write clear study notes in Markdown for a university student. Use headings, bullet points, and bold for key terms. Include definitions, formulas if relevant, and a short recap.",
      },
      {
        role: "user",
        content: `Create study notes on: ${topic}\n\nUse this Cora conversation context when helpful:\n${context.slice(0, 6000)}`,
      },
    ],
    temperature: 0.35,
    max_completion_tokens: 3000,
  })

  return content?.trim() || ""
}

export async function createFlashcardsFromTopic(
  studentDbId: number,
  topic: string,
  contextMessages: CoraWorkspaceActionMessage[],
) {
  const context = contextMessages
    .filter((m) => m.id !== "typing" && m.id !== "welcome")
    .map((m) => `${m.role === "student" ? "Student" : "Cora"}: ${m.content}`)
    .join("\n\n")

  const cards = await generateFlashcardsWithAi(topic, context)
  const { createStudentFlashcardDeck } = await import(
    "@/lib/cora/services/create-student-flashcard-deck"
  )
  const deck = await createStudentFlashcardDeck({
    studentDbId,
    title: `Cora: ${topic.slice(0, 72)}`,
    description: "Generated by Cora from workspace chat",
    topic: topic.slice(0, 120),
    cards,
  })

  return {
    deckId: deck.deckId,
    title: deck.title,
    cardCount: deck.cardCount,
    href: deck.href,
  }
}

export async function createStudyNoteFromTopic(
  studentDbId: number,
  topic: string,
  contextMessages: CoraWorkspaceActionMessage[],
  title?: string,
) {
  const context = contextMessages
    .filter((m) => m.id !== "typing" && m.id !== "welcome")
    .map((m) => `${m.role === "student" ? "Student" : "Cora"}: ${m.content}`)
    .join("\n\n")

  const bodyText = await generateStudyNoteWithAi(topic, context)
  const noteTitle = title?.trim() || `Cora notes: ${topic.slice(0, 60)}`
  const { createStudentDigitalNote } = await import(
    "@/lib/cora/services/create-student-digital-note"
  )
  return createStudentDigitalNote({
    studentDbId,
    title: noteTitle,
    bodyText,
  })
}

export async function searchPlatform(studentDbId: number, query: string) {
  const { results } = await searchPlatformForStudent(studentDbId, query)
  return {
    query,
    results,
    message: formatPlatformSearchMarkdown(query, results),
  }
}

export async function createPracticeQuiz(
  studentDbId: number,
  topic: string,
  options?: { count?: number; difficulty?: string; courseId?: number | null },
) {
  const result = await generatePracticeQuizForStudent({
    studentDbId,
    topicQuery: topic,
    count: options?.count,
    difficulty: options?.difficulty,
    courseId: options?.courseId,
  })

  return {
    attemptId: result.attemptId,
    topic: result.topic,
    questionCount: result.questionCount,
    questions: result.questions,
    href: result.href,
  }
}
